name: Flair
main: tc.oc.flair.Flair
version: ${project.version}
author: Overcast Network 

commands:
  flair:
    description: Reloads flairs
    usage: /<command>

permissions:
  flair.reload:
    description: Allows reloading
    default: op
